#PBS -M william.trouleau@epfl.ch
#PBS -l cput = 03:00:00
#PBS -l mem = 1024mb
# you want to receive an email messages when your job is started and when it's
finished (or blocked)
#PBS -m be
# the name you want to assign to this job
#PBS -N recommender_tuning


cd $HOME/trailhead/Crossroads

echo "executed on $HOSTNAME"
echo "execution started at:  $(date)"

./main.py -K $1

echo "execution finished at: $(date)"